export const CardboardClassNamePrefix = 'cb';
export type IIconNames = CardboardIconNames | string;
export type CardboardIconNames =
    | 'Add'
    | 'Chart'
    | 'Color'
    | 'CubeShape'
    | 'Database'
    | 'Delete'
    | 'DeveloperTools'
    | 'Design'
    | 'Edit'
    | 'EntryView'
    | 'Home'
    | 'Info'
    | 'Link'
    | 'LinkedDatabase'
    | 'MapLayers'
    | 'MoreVertical'
    | 'MultiSelect'
    | 'NumberField'
    | 'Org'
    | 'ProductVariant'
    | 'Ringer'
    | 'Search'
    | 'Shapes'
    | 'SpeedHigh'
    | 'View';